"""DeepSeek provider with auditable, schema-guided decision normalization.

The model remains responsible for selecting the Skill, arguments, hypotheses,
and stopping decision. The adapter only normalizes common JSON field aliases
and supplies explicitly marked administrative placeholders when DeepSeek omits
non-executable commentary fields. The raw model payload is retained in provider
metadata for audit.
"""
from __future__ import annotations

import json
import os
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Mapping, Protocol

from .contracts import ContractError, require_valid_agent_decision


SYSTEM_PROMPT = r"""You control an evidence-generating finite-element workflow.

The broad Skill categories are administrative only. Never infer a physical
mechanism from a keyword. Keep observations separate from interpretations, and
treat mechanisms as competing hypotheses that can be supported, challenged, or
left unresolved by artifacts.

Return exactly one JSON object and no Markdown. Use this exact top-level shape:
{
  "analysis_summary": "your current engineering judgment",
  "hypotheses": [{
    "id": "H1",
    "statement": "testable statement",
    "status": "candidate|supported|challenged|unknown",
    "evidence_refs": ["existing artifact IDs only"],
    "falsifier": "evidence that would challenge it"
  }],
  "evidence_assessment": [{
    "observation": "what an artifact directly shows",
    "interpretation": "what it may mean",
    "evidence_refs": ["existing artifact IDs only"],
    "confidence": "low|medium|high"
  }],
  "decision": {
    "type": "call_skill",
    "skill": "exact name from skill_catalog",
    "arguments": {},
    "purpose": "why this is the smallest discriminating action",
    "expected_evidence": ["evidence expected from the Skill"],
    "preserve_invariants": ["controlled variables that must not change"]
  },
  "uncertainties": ["remaining uncertainty"]
}

For a final answer, decision must instead be:
{
  "type": "finish",
  "conclusion": "evidence-bounded conclusion",
  "supported_scope": ["what the evidence supports"],
  "unsupported_scope": ["what remains outside scope"],
  "evidence_refs": ["existing artifact IDs"],
  "recommended_follow_up": "optional next step"
}

For indispensable missing user information, decision may be:
{
  "type": "need_user_input",
  "questions": ["specific question"],
  "reason": "why no available Skill can generate the evidence"
}

Use the keys skill and arguments, not skill_name and input. Choose exactly one
next action. Use only a Skill listed in skill_catalog. Before finishing, satisfy
the case finish requirements using real artifacts. Prefer the smallest controlled
calculation or model change that separates competing explanations. Never certify
that the whole finite-element model is correct.
"""


class DecisionProvider(Protocol):
    def decide(self, packet: dict[str, Any]) -> tuple[dict[str, Any], dict[str, Any]]: ...


class ProviderError(RuntimeError):
    pass


def _nonempty_text(value: Any, default: str) -> str:
    text = str(value).strip() if value is not None else ""
    return text or default


def _string_list(value: Any, *, default: list[str] | None = None) -> list[str]:
    if isinstance(value, str) and value.strip():
        return [value.strip()]
    if isinstance(value, list):
        rows = [str(item).strip() for item in value if str(item).strip()]
        if rows:
            return rows
    return list(default or [])


def _artifact_ids(packet: Mapping[str, Any]) -> list[str]:
    rows: list[str] = []
    for item in packet.get("artifact_index", []):
        if isinstance(item, Mapping) and item.get("artifact_id"):
            rows.append(str(item["artifact_id"]))
    return rows


def _skill_outputs(packet: Mapping[str, Any], skill_name: str) -> list[str]:
    for item in packet.get("skill_catalog", []):
        if isinstance(item, Mapping) and str(item.get("name")) == skill_name:
            outputs = _string_list(item.get("produces_artifact_kinds"))
            if outputs:
                return outputs
    return ["new evidence artifact"]


def _normalize_hypotheses(
    value: Any, *, evidence_refs: list[str], selected_skill: str | None
) -> tuple[list[dict[str, Any]], list[str]]:
    notes: list[str] = []
    normalized: list[dict[str, Any]] = []
    if isinstance(value, list):
        for index, item in enumerate(value, start=1):
            if isinstance(item, str) and item.strip():
                normalized.append({
                    "id": f"H{index}",
                    "statement": item.strip(),
                    "status": "candidate",
                    "evidence_refs": evidence_refs,
                    "falsifier": "Evidence generated by the selected controlled action."
                })
                notes.append(f"hypotheses[{index - 1}] string expanded to contract object")
            elif isinstance(item, Mapping):
                normalized.append({
                    **dict(item),
                    "id": _nonempty_text(item.get("id"), f"H{index}"),
                    "statement": _nonempty_text(
                        item.get("statement") or item.get("hypothesis"),
                        "The governing explanation remains unresolved."
                    ),
                    "status": (
                        str(item.get("status"))
                        if str(item.get("status")) in {"candidate", "supported", "challenged", "unknown"}
                        else "unknown"
                    ),
                    "evidence_refs": _string_list(
                        item.get("evidence_refs") or item.get("evidence"),
                        default=evidence_refs
                    ),
                    "falsifier": _nonempty_text(
                        item.get("falsifier") or item.get("discriminating_test"),
                        "Evidence generated by the selected controlled action."
                    )
                })
    if normalized:
        return normalized, notes
    notes.append("administrative unresolved hypothesis inserted because model omitted hypotheses")
    action = selected_skill or "the selected next action"
    return [{
        "id": "H_unresolved_1",
        "statement": (
            "The current artifacts do not yet distinguish the competing modeling "
            f"explanations; {action} is proposed to generate evidence."
        ),
        "status": "unknown",
        "evidence_refs": evidence_refs,
        "falsifier": "A controlled result that clearly separates the competing explanations."
    }], notes


def _normalize_evidence_assessment(value: Any) -> tuple[list[dict[str, Any]], list[str]]:
    notes: list[str] = []
    rows: list[dict[str, Any]] = []
    if isinstance(value, list):
        for index, item in enumerate(value):
            if not isinstance(item, Mapping):
                continue
            observation = item.get("observation") or item.get("fact")
            interpretation = item.get("interpretation") or item.get("meaning")
            if not observation or not interpretation:
                continue
            rows.append({
                **dict(item),
                "observation": str(observation),
                "interpretation": str(interpretation),
                "evidence_refs": _string_list(item.get("evidence_refs") or item.get("evidence"))
            })
            if "evidence_refs" not in item:
                notes.append(f"evidence_assessment[{index}] evidence alias normalized")
    return rows, notes


def normalize_agent_payload(
    raw_payload: Mapping[str, Any], packet: Mapping[str, Any]
) -> tuple[dict[str, Any], list[str]]:
    """Normalize common response aliases without making a physics decision."""
    payload = dict(raw_payload)
    notes: list[str] = []
    raw_decision: Any = payload.get("decision", payload.get("action"))
    if raw_decision is None and payload.get("type") in {"call_skill", "finish", "need_user_input"}:
        raw_decision = payload
        notes.append("top-level action wrapped as decision")
    if not isinstance(raw_decision, Mapping):
        return payload, notes

    decision = dict(raw_decision)
    decision_type = str(
        decision.get("type")
        or decision.get("action_type")
        or ("call_skill" if decision.get("skill_name") or decision.get("skill") else "")
    )
    decision["type"] = decision_type
    recent_refs = _artifact_ids(packet)[-4:]
    selected_skill: str | None = None

    if decision_type == "call_skill":
        selected_skill = _nonempty_text(
            decision.get("skill") or decision.get("skill_name")
            or decision.get("tool") or decision.get("name"), ""
        )
        arguments = decision.get("arguments")
        if not isinstance(arguments, Mapping):
            for alias in ("input", "args", "parameters"):
                if isinstance(decision.get(alias), Mapping):
                    arguments = decision[alias]
                    notes.append(f"decision.{alias} normalized to decision.arguments")
                    break
        if not isinstance(arguments, Mapping):
            arguments = {}
        if "skill" not in decision and selected_skill:
            notes.append("decision.skill_name/tool/name normalized to decision.skill")
        decision.update({
            "skill": selected_skill,
            "arguments": dict(arguments),
            "purpose": _nonempty_text(
                decision.get("purpose") or decision.get("reason")
                or payload.get("analysis_summary") or payload.get("analysis"),
                "Execute the model-selected Skill to generate discriminating evidence."
            ),
            "expected_evidence": _string_list(
                decision.get("expected_evidence") or decision.get("expected_outputs")
                or decision.get("outputs"),
                default=_skill_outputs(packet, selected_skill)
            ),
            "preserve_invariants": _string_list(
                decision.get("preserve_invariants") or decision.get("controlled_variables")
                or decision.get("invariants")
            )
        })
    elif decision_type == "finish":
        decision["conclusion"] = _nonempty_text(
            decision.get("conclusion") or decision.get("answer"), ""
        )
        if "supported_scope" not in decision and decision.get("scope"):
            decision["supported_scope"] = _string_list(decision.get("scope"))
            notes.append("decision.scope normalized to supported_scope")
        if "evidence_refs" not in decision and decision.get("evidence"):
            decision["evidence_refs"] = _string_list(decision.get("evidence"))
            notes.append("decision.evidence normalized to evidence_refs")
    elif decision_type == "need_user_input":
        decision["questions"] = _string_list(decision.get("questions") or decision.get("question"))
        decision["reason"] = _nonempty_text(decision.get("reason") or decision.get("purpose"), "")

    hypotheses, hypothesis_notes = _normalize_hypotheses(
        payload.get("hypotheses"), evidence_refs=recent_refs, selected_skill=selected_skill
    )
    assessment, assessment_notes = _normalize_evidence_assessment(payload.get("evidence_assessment"))
    notes.extend(hypothesis_notes)
    notes.extend(assessment_notes)

    return {
        **payload,
        "analysis_summary": _nonempty_text(
            payload.get("analysis_summary") or payload.get("analysis")
            or payload.get("reasoning_summary") or payload.get("summary")
            or decision.get("purpose"),
            "DeepSeek selected the next evidence-generating action but omitted a narrative summary."
        ),
        "hypotheses": hypotheses,
        "evidence_assessment": assessment,
        "decision": decision,
        "uncertainties": _string_list(
            payload.get("uncertainties") or payload.get("unknowns") or payload.get("limitations"),
            default=["The current evidence remains insufficient to distinguish all modeling explanations."]
        )
    }, notes


@dataclass
class DeepSeekProvider:
    api_key: str
    model: str = "deepseek-v4-pro"
    base_url: str = "https://api.deepseek.com"
    max_tokens: int = 7000
    correction_attempts: int = 3

    @classmethod
    def from_environment(cls, *, model: str | None = None) -> "DeepSeekProvider":
        api_key = os.environ.get("DEEPSEEK_API_KEY", "").strip()
        if not api_key:
            raise ProviderError("DEEPSEEK_API_KEY is not set")
        return cls(api_key=api_key, model=model or os.environ.get("DEEPSEEK_MODEL", "deepseek-v4-pro"))

    def decide(self, packet: dict[str, Any]) -> tuple[dict[str, Any], dict[str, Any]]:
        try:
            from openai import OpenAI
        except ImportError as exc:
            raise ProviderError("openai package is required for DeepSeekProvider") from exc

        client = OpenAI(api_key=self.api_key, base_url=self.base_url)
        messages: list[dict[str, str]] = [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": json.dumps(packet, ensure_ascii=False, separators=(",", ":"))}
        ]
        last_text = ""
        last_errors: list[str] = []
        last_raw_payload: Any = None

        for attempt in range(self.correction_attempts + 1):
            try:
                response = client.chat.completions.create(
                    model=self.model,
                    messages=messages,
                    response_format={"type": "json_object"},
                    max_tokens=self.max_tokens,
                    extra_body={"thinking": {"type": "enabled"}}
                )
            except Exception as exc:
                if attempt >= self.correction_attempts:
                    raise ProviderError(
                        f"DeepSeek API call failed after {attempt + 1} attempts: {type(exc).__name__}: {exc}"
                    ) from exc
                time.sleep(2 ** attempt)
                continue

            message = response.choices[0].message
            last_text = message.content or ""
            normalization_notes: list[str] = []
            try:
                raw_payload = json.loads(last_text)
                last_raw_payload = raw_payload
                if not isinstance(raw_payload, Mapping):
                    raise ContractError("model response JSON must be an object")
                payload, normalization_notes = normalize_agent_payload(raw_payload, packet)
                require_valid_agent_decision(payload)
            except (json.JSONDecodeError, ContractError) as exc:
                last_errors = [str(exc)]
                if attempt >= self.correction_attempts:
                    break
                messages.extend([
                    {"role": "assistant", "content": last_text or "{}"},
                    {"role": "user", "content": (
                        "Return a corrected complete JSON object using the exact keys in the system template. "
                        "Do not omit analysis_summary, hypotheses, evidence_assessment, uncertainties, purpose, "
                        "expected_evidence, or preserve_invariants. Validation error: " + str(exc)
                    )}
                ])
                continue

            usage = getattr(response, "usage", None)
            metadata: dict[str, Any] = {
                "provider": "deepseek",
                "requested_model": self.model,
                "response_model": getattr(response, "model", self.model),
                "finish_reason": response.choices[0].finish_reason,
                "attempt": attempt + 1,
                "raw_model_payload": last_raw_payload,
                "normalization_applied": bool(normalization_notes),
                "normalization_notes": normalization_notes
            }
            if usage is not None:
                metadata["usage"] = usage.model_dump() if hasattr(usage, "model_dump") else {
                    "prompt_tokens": getattr(usage, "prompt_tokens", None),
                    "completion_tokens": getattr(usage, "completion_tokens", None),
                    "total_tokens": getattr(usage, "total_tokens", None)
                }
            if getattr(message, "reasoning_content", None):
                metadata["reasoning_content_present"] = True
            return payload, metadata

        raise ProviderError(
            "DeepSeek returned an invalid decision after correction attempts: "
            + " | ".join(last_errors or [last_text[:500]])
        )


@dataclass
class ReplayProvider:
    decisions: list[dict[str, Any]]
    index: int = 0

    @classmethod
    def from_path(cls, path: str | Path) -> "ReplayProvider":
        payload = json.loads(Path(path).read_text(encoding="utf-8"))
        if not isinstance(payload, list):
            raise ProviderError("replay decision file must contain a JSON array")
        return cls(decisions=[dict(item) for item in payload])

    def decide(self, packet: dict[str, Any]) -> tuple[dict[str, Any], dict[str, Any]]:
        del packet
        if self.index >= len(self.decisions):
            raise ProviderError("replay provider ran out of decisions")
        payload = self.decisions[self.index]
        self.index += 1
        require_valid_agent_decision(payload)
        return payload, {"provider": "replay", "decision_index": self.index - 1, "model": "deterministic-replay"}
