"""Element-wise ZZ + Doerfler AFEM loop, realized through Gmsh remeshing.

Deployment contract (faithful to Doerfler 1996):

* the estimator object is the element (ZZ recovery indicator eta_K);
* marking is bulk marking with parameter theta over element indicators;
* refinement halves the local target size of marked elements only,
  the new mesh is generated by Gmsh from the resulting nodal size map
  (remeshing-realized refinement -- the framework-wide refinement atom);
* the loop iterates SOLVE -> ESTIMATE -> MARK -> REMESH until the
  stopping test, it is never "two rounds and declare victory".

Stopping: empty marked set, DOF cap, or hard cap on rounds.  Error
stagnation is recorded as a diagnostic, never used to stop.
"""

from __future__ import annotations

import numpy as np

from ..experiment import FemRunner, initial_mesh
from ..indicators import zz_indicator
from ..marking import dorfler_mark
from ..mesher import Mesh, generate_mesh
from ..sizefield import NodalSizeField


def refine_size_map(mesh: Mesh, marked: np.ndarray, *, factor: float = 0.5) -> np.ndarray:
    """Per-node target size: current size, halved on nodes of marked elements."""

    h_node = mesh.node_sizes.copy()
    target = h_node.copy()
    marked_nodes = np.unique(mesh.cells[marked].ravel())
    target[marked_nodes] = factor * h_node[marked_nodes]
    return target


def run_dorfler(
    runner: FemRunner,
    *,
    theta: float = 0.5,
    max_rounds: int = 12,
    n_eq_cap: int | None = None,
    gradation: float = 0.9,
    method: str = "dorfler_zz",
    require_reference: bool = True,
) -> None:
    problem = runner.problem
    if require_reference:
        runner.ensure_reference()
    if n_eq_cap is None:
        if runner.reference is None:
            raise ValueError("n_eq_cap required when no reference is loaded")
        n_eq_cap = runner.reference.n_equations

    mesh = initial_mesh(problem)
    for cycle in range(max_rounds + 1):
        post, rec = runner.solve_mesh(
            mesh, method=method, stage=f"cycle{cycle}", extra={"theta": theta}
        )
        eta2 = zz_indicator(problem, post)
        rec.extra["sum_eta2"] = float(eta2.sum())
        if cycle >= max_rounds:
            rec.extra["stop"] = "round_cap"
            break
        if rec.n_equations >= n_eq_cap:
            rec.extra["stop"] = "dof_cap"
            break
        marked = dorfler_mark(eta2, theta)
        rec.extra["n_marked"] = int(len(marked))
        if len(marked) == 0:
            rec.extra["stop"] = "empty_marking"
            break
        target = refine_size_map(mesh, marked)
        field = NodalSizeField(
            mesh, target, gradation=gradation, h_min=problem.h_min, h_max=problem.h0
        )
        mesh = generate_mesh(problem, field)
